api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        formats:
            jsonld: [ 'application/ld+json' ]
            json: [ 'application/json' ]
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
